name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Obtener el código fuente
    
    - name: Set up Node.js
      uses: actions/setup-node@v3  # Asegurarse de que Node.js esté configurado
    
    - name: Install dependencies
      run: npm install  # Instalar dependencias
    
    - name: Run build
      run: npm run build  # Ejecutar el build
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist  # Corregido 'patch' a 'path'

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Obtener el código fuente
    
    - name: Set up Node.js
      uses: actions/setup-node@v3  # Actualizar a la última versión compatible
      with:
        node-version: '20'  # Configura Node.js versión 14
    
    - name: Install dependencies
      run: npm install  # Instalar dependencias
    
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist  # Corregido 'patch' a 'path'
    
    - name: Run unit tests
      run: npm test  # Ejecutar pruebas unitarias

  deploy:
    needs: [build, test]  # Asegura que las pruebas se ejecuten antes de este paso
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Obtener el código fuente
    
    - name: Set up Node.js
      uses: actions/setup-node@v3  # Configurar Node.js
    
    - name: Install dependencies
      run: npm install  # Instalar dependencias necesarias

    - name: Trigger deployment
      if: ${{ github.event_name == 'push' }}
      run: |
        curl -X POST https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        echo "Deployment triggered."

  tag_release:
    needs: deploy  # Asegura que el 'build' se ejecute antes de este paso
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Obtener el código fuente

    - name: Bump version and push tag
      if: ${{ github.event_name == 'push' }}
      uses: anothrNick/github-tag-action@1.71.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}